#server.port=8888
#spring.datasource.url=jdbc:mysql://localhost:3306/db_springsecurity_jwt?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=true&useUnicode=yes&useLegacyDatetimeCode=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
#app.jwtSecret=@zeRtY193!
##1*24*60*60*1000; 1 jours
#app.jwtExpirationMs=86400000
#spring.mail.host=localhost
#spring.mail.port=1025
#spring.mail.username=hamzaEzzakri
#spring.mail.password=JWTSecurity
#spring.mail.properties.mail.smtp.ssl.trust=*
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#app.email=zakri7740@gmail.com
#app.personal=Hamza Ezzakri

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create

  mail:
    properties:
      mail:
        smtp:
          ssl:
            trust: '*'
          starttls:
            enable: true
          auth: true

    host: localhost
    username: hamzaEzzakri
    port: 1025
    password: JWTSecurity

  datasource:
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/db_springsecurity_jwt?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=true&useUnicode=yes&useLegacyDatetimeCode=false&serverTimezone=UTC

  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: 'false'

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 100807539253-jouoclkserk7odua1oanl5bj25q2vjsd.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile

app:
  email: MtisteApp@gmail.com
  personal: Mtiste
  jwtSecret: ml3@oO33sPfe
  jwtExpirationMs: 86400000

server:
  port: 8888
  servlet:
    context-path: /api



